-- AlterTable
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "npCityRef" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lat" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lng" DOUBLE PRECISION;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "googlePlaceId" TEXT;
