ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fxWriteOffAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fxWriteOffNote" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fxWriteOffAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "fxWriteOffByUserId" TEXT;

ALTER TABLE "Order" ADD CONSTRAINT "Order_fxWriteOffByUserId_fkey"
  FOREIGN KEY ("fxWriteOffByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
