/** Рядки оболонки модалки: v2 → UK (§28.10), інакше EN як раніше. */
export function getContactModalStrings(v2: boolean) {
  if (v2) {
    return {
      titleContact: "Контакт",
      titleNew: "Новий контакт",
      tabMain: "Огляд",
      tabOrders: "Замовлення",
      tabDelivery: "Доставка",
      tabTasks: "Задачі",
      tabHistory: "Історія змін",
      sectionAbout: "Про контакт",
      sectionActivity: "Активність",
      sectionOrders: "Замовлення",
      sectionTasks: "Задачі",
      sectionChangeHistory: "Історія змін",
      close: "Закрити",
      addOrder: "+ Замовлення",
      resetStorePassword: "Скинути пароль магазину",
      cancel: "Скасувати",
      save: "Зберегти",
      saving: "Збереження…",
      openCompany: "Відкрити компанію",
      ordersSaveFirst: "Збережіть контакт, щоб переглянути замовлення.",
      tasksSaveFirst: "Збережіть контакт, щоб керувати задачами.",
      historySaveFirst: "Збережіть контакт, щоб бачити історію змін.",
      noHistory: "Поки немає записів історії.",
      cardLoadError: "Не вдалося завантажити зведення KPI (спробуйте оновити сторінку).",
      quickCall: "Дзвінок",
      quickEmail: "Email",
      quickTelegram: "Telegram",
      quickVisit: "Візит",
      quickOrderShort: "Замовлення",
      quickTask: "Задача",
      quickPayment: "Оплата",
      metaManager: "Менеджер",
      metaNoCompany: "Без компанії",
      tooltipNoPhone: "Немає номера телефону",
      resetPasswordTitle: "Скидання пароля магазину",
      resetPasswordClose: "Закрити",
      resetPasswordErrorGeneric:
        "У контакта немає облікового запису в магазині або сталася помилка.",
      resetPasswordIntro:
        "Тимчасовий пароль і посилання для встановлення свого пароля (діє 24 год):",
      resetPasswordTempLabel: "Тимчасовий пароль:",
      copy: "Копіювати",
      resetPasswordLinkLabel: "Посилання для встановлення пароля:",
      openInNewTab: "Відкрити в новій вкладці",
      copyLink: "Копіювати посилання",
      resetPasswordAmberHint:
        "Щоб отримати готове посилання, вкажіть «Публічна URL вітрини» в Налаштування → Інтернет-магазин або задайте змінну NEXT_PUBLIC_STORE_PUBLIC_URL при збірці CRM. Нижче — токен для ручної збірки URL.",
      tokenLabel: "Токен:",
      tokenDiagnosticLabel: "Токен (для діагностики):",
      errFirstNameRequired: "Вкажіть ім'я.",
      errLastNameRequired: "Вкажіть прізвище.",
      errPhoneRequired: "Вкажіть телефон.",
      errLoadContactFallback: "Не вдалося завантажити контакт.",
      errGenericAction: "Помилка",
      visitAlertSaveContactFirst:
        "Спочатку збережіть контакт і вкажіть адресу з координатами, щоб запланувати візит.",
      visitAlertSuccess: "Візит додано до запланованих.",
      visitTitleDefault: "Візит",
      visitScheduleErrorFallback: "Не вдалося запланувати візит",
      mapsNoApiKey:
        "Ключ Google Maps не налаштовано. Автодоповнення адреси працює лише як звичайний текст.",
      mapsConfigLoadFailed: "Не вдалося завантажити налаштування Google Maps.",
      addressServiceUnavailable: "Сервіс адрес тимчасово недоступний.",
    } as const;
  }
  return {
    titleContact: "Contact",
    titleNew: "New contact",
    tabMain: "Main",
    tabOrders: "Orders",
    tabDelivery: "Delivery profiles",
    tabTasks: "Tasks",
    tabHistory: "Change history",
    sectionAbout: "About contact",
    sectionActivity: "Activity",
    sectionOrders: "Orders",
    sectionTasks: "Tasks",
    sectionChangeHistory: "Change history",
    close: "Close",
    addOrder: "+ Order",
    resetStorePassword: "Reset store password",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    openCompany: "Open company",
    ordersSaveFirst: "Save the contact first to see orders.",
    tasksSaveFirst: "Save the contact first to manage tasks.",
    historySaveFirst: "Save the contact first to see change history.",
    noHistory: "No change history yet.",
    cardLoadError: "Could not load card summary.",
    quickCall: "Call",
    quickEmail: "Email",
    quickTelegram: "Telegram",
    quickVisit: "Visit",
    quickOrderShort: "Order",
    quickTask: "Task",
    quickPayment: "Payment",
    metaManager: "Manager",
    metaNoCompany: "No company",
    tooltipNoPhone: "No phone number",
    resetPasswordTitle: "Store password reset",
    resetPasswordClose: "Close",
    resetPasswordErrorGeneric:
      "No storefront account for this contact or an error occurred.",
    resetPasswordIntro: "Temporary password and link to set your own password (valid 24h):",
    resetPasswordTempLabel: "Temporary password:",
    copy: "Copy",
    resetPasswordLinkLabel: "Set-password link:",
    openInNewTab: "Open in new tab",
    copyLink: "Copy link",
    resetPasswordAmberHint:
      "To get a ready-made link, set «Public storefront URL» in Settings → Store or set NEXT_PUBLIC_STORE_PUBLIC_URL at CRM build time. Below is the token for manual URL assembly.",
    tokenLabel: "Token:",
    tokenDiagnosticLabel: "Token (diagnostic):",
    errFirstNameRequired: "First name is required",
    errLastNameRequired: "Last name is required",
    errPhoneRequired: "Phone is required",
    errLoadContactFallback: "Failed to load contact",
    errGenericAction: "Failed",
    visitAlertSaveContactFirst:
      "Save the contact first and fill in the address to schedule a visit.",
    visitAlertSuccess: "Visit added to planned backlog.",
    visitTitleDefault: "Visit",
    visitScheduleErrorFallback: "Failed to schedule visit",
    mapsNoApiKey:
      "Google Maps API key is not configured. Address autocomplete works only as plain text.",
    mapsConfigLoadFailed: "Failed to load Google Maps configuration.",
    addressServiceUnavailable: "Address service temporarily unavailable.",
  } as const;
}

export type ContactModalStrings = ReturnType<typeof getContactModalStrings>;
