plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
  id 'com.google.devtools.ksp'
}

group = 'expo.modules.crnativetracking'
version = '1.0.0'

android {
  namespace "expo.modules.crnativetracking"
}

dependencies {
  implementation "com.google.android.gms:play-services-location:21.3.0"
  implementation "androidx.room:room-runtime:2.6.1"
  implementation "androidx.room:room-ktx:2.6.1"
  ksp "androidx.room:room-compiler:2.6.1"
  implementation "androidx.datastore:datastore-preferences:1.1.1"
  implementation "androidx.work:work-runtime-ktx:2.9.1"
}
